create table accounts (
    id             bigint generated by default as identity primary key,
    account_number varchar(10)    not null unique,
    holder_name    varchar(255)   not null,
    currency       varchar(3)     not null,
    balance        numeric(19, 2) not null
);

create table transfers (
    id           bigint generated by default as identity primary key,
    from_account varchar(10)    not null,
    to_account   varchar(10)    not null,
    amount       numeric(19, 2) not null,
    reference    varchar(35),
    signature    varchar(64)    not null,
    created_at   timestamp      not null
);
